#!/bin/zsh

# Inspired on https://github.com/unixorn/zsh-quickstart-kit/blob/master/zsh/.zgen-setup
# Also: https://github.com/faceleg/dotfiles/blob/master/configuration/zshrc
# https://github.com/b4b4r07/dotfiles/blob/master/.zsh/zplug.zsh
# https://github.com/zdharma/zplugin

ZPLG_HOME="${ZDOTDIR:-$HOME}/.zplugin"
install_zplugin() {
  if [[ ! -d $ZPLG_HOME ]]; then
    echo "foo"
    mkdir "$ZPLG_HOME"
    chmod g-rwX "$ZPLG_HOME"
  fi
  if [[ ! -d $ZPLG_HOME/bin ]]; then
    echo "Installing zplugin..."
    git clone --depth 10 https://github.com/zdharma/zplugin.git "$ZPLG_HOME/bin"
  fi
}

zplugin() {
  install_zplugin
  source "$HOME/.zplugin/bin/zplugin.zsh"
  autoload -Uz _zplugin
  (( ${+_comps} )) && _comps[zplugin]=_zplugin
  zplugin ice wait"0" blockf  #  load 0 seconds (about 150 ms exactly) after prompt,
  zplugin light zsh-users/zsh-completions
  zplugin ice wait"0" atload"_zsh_autosuggest_start"
  zplugin light zsh-users/zsh-autosuggestions
  zplugin ice wait"0" atinit"zpcompinit; zpcdreplay"
  zplugin light zdharma/fast-syntax-highlighting
  setopt promptsubst
  zplugin ice wait"0" lucid
  zplugin snippet OMZ::lib/git.zsh
  zplugin ice wait"0" atload"unalias grv" lucid
  zplugin snippet OMZ::plugins/git/git.plugin.zsh

  zplugin snippet OMZ::lib/key-bindings.zsh
  #zplugin snippet OMZ::plugins/docker/_docker
  #zplugin ice wait"0"
  #zplugin ice atinit'zmodload zsh/zprof' atload'zprof | head; zmodload -u zsh/zprof'
  zplugin light bhilburn/powerlevel9k

  #zplugin snippet "https://github.com/chriskempson/base16-shell/blob/master/scripts/base16-tomorrow-night.sh"

  #zplugin self-update
  #zplugin update --all
}

zplugin
