#!/bin/zsh

# Inspired on https://github.com/unixorn/zsh-quickstart-kit/blob/master/zsh/.zgen-setup
# Also: https://github.com/faceleg/dotfiles/blob/master/configuration/zshrc
# https://github.com/b4b4r07/dotfiles/blob/master/.zsh/zplug.zsh

ZPLUG_HOME="$HOME/.zplug"

function intall_zplug() {
  if [[ ! -d $ZPLUG_HOME ]]; then
    echo "Installing zplug..."
    git clone https://github.com/zplug/zplug.git "$ZPLUG_HOME"
  fi
}

function load_plugin_list() {
  zplug "zsh-users/zsh-completions"
  zplug 'zsh-users/zsh-autosuggestions'
  #zplug "zsh-users/zsh-history-substring-search", defer:3
  zplug "zsh-users/zsh-syntax-highlighting", defer:2

  # 0.5 seconds
  zplug "plugins/git",         from:oh-my-zsh, ignore:oh-my-zsh.sh
  zplug "plugins/github",      from:oh-my-zsh, ignore:oh-my-zsh.sh
  #zplug "plugins/pip",         from:oh-my-zsh
  zplug "plugins/rsync",       from:oh-my-zsh, ignore:oh-my-zsh.sh
  zplug "plugins/docker",      from:oh-my-zsh, ignore:oh-my-zsh.sh
  #zplug "plugins/safe-paste",  from:oh-my-zsh  # takes 0.6 seconds

  zplug "lib/history",         from:oh-my-zsh, ignore:oh-my-zsh.sh
  zplug "lib/termsupport",     from:oh-my-zsh, ignore:oh-my-zsh.sh
  zplug "lib/key-bindings",    from:oh-my-zsh, ignore:oh-my-zsh.sh
  zplug "lib/compfix",         from:oh-my-zsh, ignore:oh-my-zsh.sh
  zplug "lib/completion",      from:oh-my-zsh, ignore:oh-my-zsh.sh
  # 0.2 seconds
  zplug "lib/clipboard",       from:oh-my-zsh, if:"[[ $OSTYPE == *darwin* ]]", ignore:oh-my-zsh.sh
  zplug "plugins/osx",         from:oh-my-zsh, if:"[[ $OSTYPE == *darwin* ]]", ignore:oh-my-zsh.sh

  zplug "chrissicool/zsh-256color", from:github, defer:2
  zplug "chriskempson/base16-shell", \
      use:"*/base16-tomorrow-night.sh"
  zplug "bhilburn/powerlevel9k", as:theme

  # cmds
  zplug "junegunn/fzf-bin", \
      as:command, \
      from:gh-r, \
      rename-to:"fzf", \
      frozen:1
  zplug "monochromegane/the_platinum_searcher", \
      as:command, \
      from:gh-r, \
      rename-to:"pt", \
      frozen:1
  zplug "motemen/ghq", \
    as:command, \
    from:gh-r, \
    rename-to:ghq
}

function main() {
  touch "$ZPLUG_HOME/packages.zsh"
  intall_zplug
  source "$ZPLUG_HOME/init.zsh"
  load_plugin_list
  zplug check || zplug install
  zplug load
}

main
