# vim: ft=shell syntax=sh

# update

# upgrade

tap homebrew/dupes
tap homebrew/versions

# for sitespeedio
# tap tobli/browsertime

# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

install lastpass-cli
install duply
install vim --override-system-vi
install zsh
install git

# a terminal multiplexer
install tmux

# so copy/paste works in tmux
install reattach-to-user-namespace
# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
install coreutils
# Install some other useful utilities like `sponge`
install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
install findutils
# Install GNU `sed`, overwriting the built-in `sed`
install gnu-sed --default-names
# Install Bash 4
# Note: don’t forget to add `/usr/local/bin/bash` to `/etc/shells` before running `chsh`.
install bash
install bash-completion

install rsync
install unrar
install getmail

# Install wget with IRI support
install wget --enable-iri


# Install other useful binaries
install ack
install curl
install bfg
install foremost
install fasd
install hashpump
install lynx
install nmap
install gzip
install p7zip
install pigz
install pv
install rename
install tig
install tree

install ctags

# a better ack/grep
install the_silver_searcher

install homebrew/dupes/grep

# dependecies for ruby
install openssl libyaml

# node with npm
install node

# docker
install docker
install boot2docker
install docker-machine
install docker-compose

# encfs
install ntfs-3g
install encfs


install youtube-dl

install lua
install luarocks

# Cask files
# taps for casks
tap caskroom/cask
tap caskroom/fonts
tap caskroom/versions

install caskroom/cask/brew-cask


# keyboard tools
cask install karabiner
cask install seil
cask install slate
cask install iterm2

cask install google-chrome
cask install font-source-code-pro

cask install libreoffice
cask install keepassx
cask install keepassx0
cask install macvim
cask install the-unarchiver

# other tools
cask install google-drive
cask install screenhero
cask install synergy

# non priority stuff
cask install firefox
cask install gnucash
cask install vlc
cask install virtualbox
cask install mjolnir

cleanup