# vim: ft=shell syntax=sh

# update

# upgrade

tap homebrew/dupes
tap homebrew/versions

# for sitespeedio
# tap tobli/browsertime

# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# === Terminal tools
install zsh
install git tig
install vim --with-lua --override-system-vi
# install nvim
install neovim/neovim/neovim
install emacs
install shellcheck
install tmux reattach-to-user-namespace tmux-mem-cpu-load
install peco
#install fzf
# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
install coreutils
# Install some other useful utilities like `sponge`
install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
install findutils
# Install GNU `sed`, overwriting the built-in `sed`
install gnu-sed --default-names

# Install other useful binaries
install ack
install curl --with-openssl
install bfg
install bats
install ctags
install foremost
install homebrew/dupes/grep
install fasd
install hashpump
install lynx
install nmap
install gzip p7zip pigz unrar
install pv
install rename
install the_silver_searcher
install tree
install wget --enable-iri
install jq

install rsync duply
install gpg
link gpg
install sshuttle
install bind

# Install Bash 4
# Note: don’t forget to add `/usr/local/bin/bash` to `/etc/shells` before running `chsh`.
install bash bash-completion

install openssl
link openssl

# dependecies for ruby
install ruby-build rbenv
install libyaml

# node with npm
install node

install docker docker-machine docker-compose

# work: java + gradle
install --universal --java subversion17
install gradle112

install ncdu
install ledger
install youtube-dl
install lastpass-cli
install getmail
install pgcli

install lua luarocks

brew tap yudai/gotty
brew install gotty

install ansifilter

# ===== Cask files
# might need sudo access
# taps for casks
tap caskroom/cask
tap caskroom/fonts
tap caskroom/versions

install caskroom/cask/brew-cask

# keyboard tools
cask install karabiner seil
cask install iterm2
cask install google-chrome

cask install java

cask install libreoffice
cask install keepassx
cask install keepassx0
cask install keeweb
cask install macvim
cask install slack
cask install font-source-code-pro
cask install spotify

# non priority stuff
cask install gnucash
cask install betterzip
cask install the-unarchiver
cask install screenhero
cask install synergy
cask install google-drive
cask install firefox
cask install vlc
cask install virtualbox
#cask install mjolnir
cask install hammerspoon
cask install google-hangouts
#cask install slate
cask install atom
cask install osxfuse

install homebrew/fuse/encfs
install ntfs-3g

cleanup