# An ansible playbook to sets up a vim/zsh/tmux environment
#
# Author: Luis Bianchin <labianchin@l433.com>
# yum install libevent-devel python-devel gcc python-pip -y && pip install ansible
---

- hosts: all

  tasks:

  - name: Determining username
    action: shell whoami
    register: whoami
    sudo: False

  - name: get epel-repo rpm RHEL6
    get_url: dest=/tmp/epel-release.rpm  url=http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
    when: ansible_os_family == 'RedHat' and ansible_lsb.major_release|int == 6
  - name: get epel-repo rpm RHEL5
    get_url: dest=/tmp/epel-release.rpm  url=http://download.fedoraproject.org/pub/epel/5/i386/epel-release-5-4.noarch.rpm
    when: ansible_os_family == 'RedHat' and ansible_lsb.major_release|int == 5
  - name: install epel-repo rpm
    yum: pkg=/tmp/epel-release.rpm state=installed

  - name: Installing zsh, vim, git, tmux, etc.
    action: yum pkg={{ item }} state=latest
    with_items:
    - zsh
    - vim-enhanced
    - git
    - tmux
    - htop
    - ack
    - curl
    - wget

  - name: Changing the default shell to zsh
    action: user shell=/bin/zsh user={{ whoami.stdout }}

- name: Adding labianchin dotfiles
  hosts: all
  sudo: False

  tasks:

  - name: Install labianchin dotfiles
    action: shell bash ~/dotfiles/install.sh